
elementoSubjetivo('abandonado',-3).
elementoSubjetivo('abandonar',-3).
elementoSubjetivo('abaratar',-3).
elementoSubjetivo('abatir',-3).
elementoSubjetivo('abdicar',-3).
elementoSubjetivo('abejas',-3).
elementoSubjetivo('abominable',-3).
elementoSubjetivo('aborrecer',-3).
elementoSubjetivo('aborto',-3).
elementoSubjetivo('abrasador',-3).
elementoSubjetivo('abrasivos',-3).
elementoSubjetivo('abrumado',-3).
elementoSubjetivo('abrumador',-3).
elementoSubjetivo('absoluto',-3).
elementoSubjetivo('abstener',-3).
elementoSubjetivo('absurdo',-3).
elementoSubjetivo('aburrido',-3).
elementoSubjetivo('aburrimiento',-3).
elementoSubjetivo('aburrir',-3).
elementoSubjetivo('abuso',-3).
elementoSubjetivo('abyecta',-3).
elementoSubjetivo('abyectos',-3).
elementoSubjetivo('accidente',-3).
elementoSubjetivo('acechar',-3).
elementoSubjetivo('acosar',-3).
elementoSubjetivo('acostumbrar',-3).
elementoSubjetivo('acritud',-3).
elementoSubjetivo('acusaciÛn',-3).
elementoSubjetivo('acusar',-3).
elementoSubjetivo('adicciÛn',-3).
elementoSubjetivo('adicto',-3).
elementoSubjetivo('adulteraciÛn',-3).
elementoSubjetivo('adulterar',-3).
elementoSubjetivo('adulterio',-3).
elementoSubjetivo('adversario',-3).
elementoSubjetivo('adversas',-3).
elementoSubjetivo('adversidad',-3).
elementoSubjetivo('advertencia',-3).
elementoSubjetivo('advertir',-3).
elementoSubjetivo('afectaciÛn',-3).
elementoSubjetivo('afectar',-3).
elementoSubjetivo('aflicciÛn',-3).
elementoSubjetivo('afligen',-3).
elementoSubjetivo('afligido',-3).
elementoSubjetivo('agitaciÛn',-3).
elementoSubjetivo('agitador',-3).
elementoSubjetivo('agitar',-3).
elementoSubjetivo('agobiado',-3).
elementoSubjetivo('agonÌa',-3).
elementoSubjetivo('agonizar',-3).
elementoSubjetivo('agoreras',-3).
elementoSubjetivo('agotamiento',-3).
elementoSubjetivo('agotar',-3).
elementoSubjetivo('agravamiento',-3).
elementoSubjetivo('agravar',-3).
elementoSubjetivo('agresiÛn',-3).
elementoSubjetivo('agresividad',-3).
elementoSubjetivo('agresivo',-3).
elementoSubjetivo('agresor',-3).
elementoSubjetivo('agrio',-3).
elementoSubjetivo('aguja',-3).
elementoSubjetivo('agujero',-3).
elementoSubjetivo('ahogarse',-3).
elementoSubjetivo('aislar',-3).
elementoSubjetivo('alardear',-3).
elementoSubjetivo('alarma',-3).
elementoSubjetivo('alboroto',-3).
elementoSubjetivo('alcohÛlico',-3).
elementoSubjetivo('alegaciones',-3).
elementoSubjetivo('alegar',-3).
elementoSubjetivo('alerta',-3).
elementoSubjetivo('alienaciÛn',-3).
elementoSubjetivo('altercaciÛn',-3).
elementoSubjetivo('altivo',-3).
elementoSubjetivo('alto',-3).
elementoSubjetivo('amable',-3).
elementoSubjetivo('amargo',-3).
elementoSubjetivo('amargura',-3).
elementoSubjetivo('ambig¸edad',-3).
elementoSubjetivo('ambiguo',-3).
elementoSubjetivo('ambivalentes',-3).
elementoSubjetivo('ambulancia',-3).
elementoSubjetivo('amenaza',-3).
elementoSubjetivo('amenazar',-3).
elementoSubjetivo('amonestar',-3).
elementoSubjetivo('amortiguador',-3).
elementoSubjetivo('ampolla',-3).
elementoSubjetivo('amputar',-3).
elementoSubjetivo('anÛmalo',-3).
elementoSubjetivo('analfabetos',-3).
elementoSubjetivo('anarquÌa',-3).
elementoSubjetivo('anarquista',-3).
elementoSubjetivo('angustia',-3).
elementoSubjetivo('angustiado',-3).
elementoSubjetivo('anhelar',-3).
elementoSubjetivo('animosidad',-3).
elementoSubjetivo('aniquilar',-3).
elementoSubjetivo('anomalÌa',-3).
elementoSubjetivo('anormal',-3).
elementoSubjetivo('ansiedad',-3).
elementoSubjetivo('ansioso',-3).
elementoSubjetivo('antagÛnicos',-3).
elementoSubjetivo('antagonismo',-3).
elementoSubjetivo('antagonista',-3).
elementoSubjetivo('antagonizar',-3).
elementoSubjetivo('anti-social',-3).
elementoSubjetivo('anticuado',-3).
elementoSubjetivo('antieconÛmica',-3).
elementoSubjetivo('antinatural',-3).
elementoSubjetivo('antipatÌa',-3).
elementoSubjetivo('anulaciÛn',-3).
elementoSubjetivo('anular',-3).
elementoSubjetivo('ap·tico',-3).
elementoSubjetivo('apagar',-3).
elementoSubjetivo('apatÌa',-3).
elementoSubjetivo('aplastado',-3).
elementoSubjetivo('aplastamiento',-3).
elementoSubjetivo('aplicar',-3).
elementoSubjetivo('apologÈtico',-3).
elementoSubjetivo('aprensivo',-3).
elementoSubjetivo('aprobaciÛn',-3).
elementoSubjetivo('aprovechar',-3).
elementoSubjetivo('apuros',-3).
elementoSubjetivo('araÒa',-3).
elementoSubjetivo('arbitrario',-3).
elementoSubjetivo('arco',-3).
elementoSubjetivo('arma',-3).
elementoSubjetivo('armar',-3).
elementoSubjetivo('arranque',-3).
elementoSubjetivo('arrastrar',-3).
elementoSubjetivo('arresto',-3).
elementoSubjetivo('arriesgar',-3).
elementoSubjetivo('arrogancia',-3).
elementoSubjetivo('arrogante',-3).
elementoSubjetivo('arruga',-3).
elementoSubjetivo('arrugar',-3).
elementoSubjetivo('artificial',-3).
elementoSubjetivo('asaltar',-3).
elementoSubjetivo('asalto',-3).
elementoSubjetivo('asco',-3).
elementoSubjetivo('asediado',-3).
elementoSubjetivo('asediar',-3).
elementoSubjetivo('asesinar',-3).
elementoSubjetivo('asesino',-3).
elementoSubjetivo('asfixiarse',-3).
elementoSubjetivo('asolado',-3).
elementoSubjetivo('asolando',-3).
elementoSubjetivo('asolar',-3).
elementoSubjetivo('asqueado',-3).
elementoSubjetivo('asqueroso',-3).
elementoSubjetivo('asustado',-3).
elementoSubjetivo('asustar',-3).
elementoSubjetivo('atÛnito',-3).
elementoSubjetivo('ata˙d',-3).
elementoSubjetivo('atacar',-3).
elementoSubjetivo('ataque',-3).
elementoSubjetivo('aterrorizado',-3).
elementoSubjetivo('aterrorizar',-3).
elementoSubjetivo('atracador',-3).
elementoSubjetivo('atractivo',-3).
elementoSubjetivo('atrocidad',-3).
elementoSubjetivo('atrofia',-3).
elementoSubjetivo('atroz',-3).
elementoSubjetivo('ausencia',-3).
elementoSubjetivo('ausentar',-3).
elementoSubjetivo('ausente',-3).
elementoSubjetivo('austera',-3).
elementoSubjetivo('autÛcrata',-3).
elementoSubjetivo('autocr·tico',-3).
elementoSubjetivo('avalancha',-3).
elementoSubjetivo('avanzar',-3).
elementoSubjetivo('avaricia',-3).
elementoSubjetivo('avaro',-3).
elementoSubjetivo('avergonzado',-3).
elementoSubjetivo('avergonzar',-3).
elementoSubjetivo('aversiÛn',-3).
elementoSubjetivo('avispa',-3).
elementoSubjetivo('ayuda',-3).
elementoSubjetivo('ayuno',-3).
elementoSubjetivo('azarosa',-3).
elementoSubjetivo('bache',-3).
elementoSubjetivo('bajo',-3).
elementoSubjetivo('bala',-3).
elementoSubjetivo('baladronada',-3).
elementoSubjetivo('balbucear',-3).
elementoSubjetivo('banal',-3).
elementoSubjetivo('bancarrota',-3).
elementoSubjetivo('bandido',-3).
elementoSubjetivo('barato',-3).
elementoSubjetivo('barra',-3).
elementoSubjetivo('barrer',-3).
elementoSubjetivo('barrera',-3).
elementoSubjetivo('bastÛn',-3).
elementoSubjetivo('bastardo',-3).
elementoSubjetivo('basto',-3).
elementoSubjetivo('basura',-3).
elementoSubjetivo('batalla',-3).
elementoSubjetivo('belicoso',-3).
elementoSubjetivo('beligerante',-3).
elementoSubjetivo('bestia',-3).
elementoSubjetivo('bestial',-3).
elementoSubjetivo('bizarro',-3).
elementoSubjetivo('blandir',-3).
elementoSubjetivo('blasfemia',-3).
elementoSubjetivo('bloque',-3).
elementoSubjetivo('bofetada',-3).
elementoSubjetivo('boicot',-3).
elementoSubjetivo('bomba',-3).
elementoSubjetivo('bombardear',-3).
elementoSubjetivo('bombardeo',-3).
elementoSubjetivo('borracho',-3).
elementoSubjetivo('borrar',-3).
elementoSubjetivo('bostezo',-3).
elementoSubjetivo('boxeador',-3).
elementoSubjetivo('breve',-3).
elementoSubjetivo('bristle',-3).
elementoSubjetivo('bruja',-3).
elementoSubjetivo('brusco',-3).
elementoSubjetivo('bruta',-3).
elementoSubjetivo('brutal',-3).
elementoSubjetivo('brutalidad',-3).
elementoSubjetivo('bullet',-3).
elementoSubjetivo('bullicioso',-3).
elementoSubjetivo('bulto',-3).
elementoSubjetivo('bum',-3).
elementoSubjetivo('bungle',-3).
elementoSubjetivo('burla',-3).
elementoSubjetivo('burlar',-3).
elementoSubjetivo('c·ncer',-3).
elementoSubjetivo('c·rcel',-3).
elementoSubjetivo('cÌnico',-3).
elementoSubjetivo('cÌrculo',-3).
elementoSubjetivo('cÛlera',-3).
elementoSubjetivo('caÌda',-3).
elementoSubjetivo('caÒÛn',-3).
elementoSubjetivo('caÛtico',-3).
elementoSubjetivo('cabeza',-3).
elementoSubjetivo('cad·ver',-3).
elementoSubjetivo('caducidad',-3).
elementoSubjetivo('calambre',-3).
elementoSubjetivo('calamidad',-3).
elementoSubjetivo('caliente',-3).
elementoSubjetivo('callejÛn',-3).
elementoSubjetivo('calumnia',-3).
elementoSubjetivo('calumniador',-3).
elementoSubjetivo('calumnioso',-3).
elementoSubjetivo('calvario',-3).
elementoSubjetivo('caminar',-3).
elementoSubjetivo('canÌbal',-3).
elementoSubjetivo('cancel',-3).
elementoSubjetivo('cancelaciÛn',-3).
elementoSubjetivo('cansado',-3).
elementoSubjetivo('cansancio',-3).
elementoSubjetivo('cansar',-3).
elementoSubjetivo('caos',-3).
elementoSubjetivo('capital',-3).
elementoSubjetivo('capitular',-3).
elementoSubjetivo('caprichoso',-3).
elementoSubjetivo('capturar',-3).
elementoSubjetivo('careen',-3).
elementoSubjetivo('carga',-3).
elementoSubjetivo('carnicerÌa',-3).
elementoSubjetivo('carrera',-3).
elementoSubjetivo('carroÒa',-3).
elementoSubjetivo('castigar',-3).
elementoSubjetivo('castigo',-3).
elementoSubjetivo('catÛdica',-3).
elementoSubjetivo('cataclismo',-3).
elementoSubjetivo('catastrofes',-3).
elementoSubjetivo('cautividad',-3).
elementoSubjetivo('cavernas',-3).
elementoSubjetivo('cazador',-3).
elementoSubjetivo('cazar',-3).
elementoSubjetivo('ceÒo',-3).
elementoSubjetivo('cebar',-3).
elementoSubjetivo('ceguera',-3).
elementoSubjetivo('celos',-3).
elementoSubjetivo('cementerio',-3).
elementoSubjetivo('censor',-3).
elementoSubjetivo('censura',-3).
elementoSubjetivo('censurable',-3).
elementoSubjetivo('censure',-3).
elementoSubjetivo('cerdo',-3).
elementoSubjetivo('cerrar',-3).
elementoSubjetivo('chafe',-3).
elementoSubjetivo('chantaje',-3).
elementoSubjetivo('chase',-3).
elementoSubjetivo('cheater',-3).
elementoSubjetivo('chillido',-3).
elementoSubjetivo('chivo',-3).
elementoSubjetivo('choque',-3).
elementoSubjetivo('cicatriz',-3).
elementoSubjetivo('ciclÛn',-3).
elementoSubjetivo('ciego',-3).
elementoSubjetivo('cieno',-3).
elementoSubjetivo('cierre',-3).
elementoSubjetivo('cinismo',-3).
elementoSubjetivo('cirugÌa',-3).
elementoSubjetivo('clamor',-3).
elementoSubjetivo('clamoroso',-3).
elementoSubjetivo('coacciÛn',-3).
elementoSubjetivo('coaccionar',-3).
elementoSubjetivo('cobarde',-3).
elementoSubjetivo('cobertura',-3).
elementoSubjetivo('coercitivas',-3).
elementoSubjetivo('cojear',-3).
elementoSubjetivo('colapso',-3).
elementoSubjetivo('colisiÛn',-3).
elementoSubjetivo('collide',-3).
elementoSubjetivo('colonia',-3).
elementoSubjetivo('colusiÛn',-3).
elementoSubjetivo('com˙n',-3).
elementoSubjetivo('combatiente',-3).
elementoSubjetivo('competencia',-3).
elementoSubjetivo('competidor',-3).
elementoSubjetivo('competir',-3).
elementoSubjetivo('complejidad',-3).
elementoSubjetivo('complejo',-3).
elementoSubjetivo('complicaciÛn',-3).
elementoSubjetivo('complicado',-3).
elementoSubjetivo('complicar',-3).
elementoSubjetivo('complicidad',-3).
elementoSubjetivo('concurso',-3).
elementoSubjetivo('condescendencia',-3).
elementoSubjetivo('condescendiente',-3).
elementoSubjetivo('conducta',-3).
elementoSubjetivo('confesar',-3).
elementoSubjetivo('confesiÛn',-3).
elementoSubjetivo('confiables',-3).
elementoSubjetivo('confinamiento',-3).
elementoSubjetivo('confiscar',-3).
elementoSubjetivo('conflicto',-3).
elementoSubjetivo('confundir',-3).
elementoSubjetivo('confusiÛn',-3).
elementoSubjetivo('confuso',-3).
elementoSubjetivo('congestiÛn',-3).
elementoSubjetivo('congestionadas',-3).
elementoSubjetivo('conmiseraciÛn',-3).
elementoSubjetivo('conmociÛn',-3).
elementoSubjetivo('conspiraciÛn',-3).
elementoSubjetivo('conspirador',-3).
elementoSubjetivo('conspirar',-3).
elementoSubjetivo('consternaciÛn',-3).
elementoSubjetivo('constraint',-3).
elementoSubjetivo('consuntivos',-3).
elementoSubjetivo('contagiosa',-3).
elementoSubjetivo('contaminaciÛn',-3).
elementoSubjetivo('contaminar',-3).
elementoSubjetivo('contemptuous',-3).
elementoSubjetivo('contra',-3).
elementoSubjetivo('contrabando',-3).
elementoSubjetivo('contradicciÛn',-3).
elementoSubjetivo('contradicen',-3).
elementoSubjetivo('contradictorio',-3).
elementoSubjetivo('contrario',-3).
elementoSubjetivo('contrarrestar',-3).
elementoSubjetivo('controversia',-3).
elementoSubjetivo('controvertido',-3).
elementoSubjetivo('corazÛn',-3).
elementoSubjetivo('corroer',-3).
elementoSubjetivo('corrosiÛn',-3).
elementoSubjetivo('corrosivo',-3).
elementoSubjetivo('corrupciÛn',-3).
elementoSubjetivo('corruptas',-3).
elementoSubjetivo('corrupto',-3).
elementoSubjetivo('corte',-3).
elementoSubjetivo('coste',-3).
elementoSubjetivo('costo',-3).
elementoSubjetivo('costoso',-3).
elementoSubjetivo('crÈdulo',-3).
elementoSubjetivo('crÈdulos',-3).
elementoSubjetivo('crÌtico',-3).
elementoSubjetivo('crÛnico',-3).
elementoSubjetivo('crimen',-3).
elementoSubjetivo('criminal',-3).
elementoSubjetivo('crisis',-3).
elementoSubjetivo('crucificar',-3).
elementoSubjetivo('crudo',-3).
elementoSubjetivo('cruel',-3).
elementoSubjetivo('crueldad',-3).
elementoSubjetivo('cruz',-3).
elementoSubjetivo('cucaracha',-3).
elementoSubjetivo('cuchillo',-3).
elementoSubjetivo('cuenta',-3).
elementoSubjetivo('cuestionable',-3).
elementoSubjetivo('cuidado',-3).
elementoSubjetivo('culpa',-3).
elementoSubjetivo('culpable',-3).
elementoSubjetivo('culpar',-3).
elementoSubjetivo('cultivar',-3).
elementoSubjetivo('curso',-3).
elementoSubjetivo('dÈbil',-3).
elementoSubjetivo('dÈficit',-3).
elementoSubjetivo('daÒar',-3).
elementoSubjetivo('daÒo',-3).
elementoSubjetivo('daga',-3).
elementoSubjetivo('dawdle',-3).
elementoSubjetivo('deber',-3).
elementoSubjetivo('debilidad',-3).
elementoSubjetivo('decadencia',-3).
elementoSubjetivo('decadente',-3).
elementoSubjetivo('decepciÛn',-3).
elementoSubjetivo('decepcionar',-3).
elementoSubjetivo('declive',-3).
elementoSubjetivo('decomiso',-3).
elementoSubjetivo('dedo',-3).
elementoSubjetivo('defecto',-3).
elementoSubjetivo('defectuoso',-3).
elementoSubjetivo('defensa',-3).
elementoSubjetivo('defiant',-3).
elementoSubjetivo('deficiencia',-3).
elementoSubjetivo('deficiente',-3).
elementoSubjetivo('definido',-3).
elementoSubjetivo('deforme',-3).
elementoSubjetivo('degenerada',-3).
elementoSubjetivo('degradar',-3).
elementoSubjetivo('delincuencia',-3).
elementoSubjetivo('delincuente',-3).
elementoSubjetivo('delirium',-3).
elementoSubjetivo('demanda',-3).
elementoSubjetivo('demandado',-3).
elementoSubjetivo('demandante',-3).
elementoSubjetivo('demasiado',-3).
elementoSubjetivo('demente',-3).
elementoSubjetivo('demoler',-3).
elementoSubjetivo('demonio',-3).
elementoSubjetivo('denegaciÛn',-3).
elementoSubjetivo('denegar',-3).
elementoSubjetivo('dentista',-3).
elementoSubjetivo('denunciar',-3).
elementoSubjetivo('dependencia',-3).
elementoSubjetivo('dependiente',-3).
elementoSubjetivo('deplorables',-3).
elementoSubjetivo('deploramos',-3).
elementoSubjetivo('depravado',-3).
elementoSubjetivo('depreciaciÛn',-3).
elementoSubjetivo('depreciarse',-3).
elementoSubjetivo('depresiÛn',-3).
elementoSubjetivo('deprimido',-3).
elementoSubjetivo('deprimir',-3).
elementoSubjetivo('derogaciÛn',-3).
elementoSubjetivo('derramar',-3).
elementoSubjetivo('derrocar',-3).
elementoSubjetivo('derrota',-3).
elementoSubjetivo('desacato',-3).
elementoSubjetivo('desacreditar',-3).
elementoSubjetivo('desacuerdo',-3).
elementoSubjetivo('desafÌo',-3).
elementoSubjetivo('desafiar',-3).
elementoSubjetivo('desafortunado',-3).
elementoSubjetivo('desagradable',-3).
elementoSubjetivo('desagradecido',-3).
elementoSubjetivo('desagrado',-3).
elementoSubjetivo('desalentar',-3).
elementoSubjetivo('desaliento',-3).
elementoSubjetivo('desalojar',-3).
elementoSubjetivo('desamparado',-3).
elementoSubjetivo('desanimado',-3).
elementoSubjetivo('desapariciÛn',-3).
elementoSubjetivo('desaprobaciÛn',-3).
elementoSubjetivo('desaprueba',-3).
elementoSubjetivo('desarmar',-3).
elementoSubjetivo('desarraigar',-3).
elementoSubjetivo('desastre',-3).
elementoSubjetivo('desastroso',-3).
elementoSubjetivo('desbordar',-3).
elementoSubjetivo('descarado',-3).
elementoSubjetivo('descenso',-3).
elementoSubjetivo('descomponer',-3).
elementoSubjetivo('descomposiciÛn',-3).
elementoSubjetivo('desconcertar',-3).
elementoSubjetivo('desconcierto',-3).
elementoSubjetivo('desconfianza',-3).
elementoSubjetivo('desconfiar',-3).
elementoSubjetivo('desconocido',-3).
elementoSubjetivo('descontento',-3).
elementoSubjetivo('descorazonar',-3).
elementoSubjetivo('descuidar',-3).
elementoSubjetivo('desdÈn',-3).
elementoSubjetivo('desdeÒoso',-3).
elementoSubjetivo('desdicha',-3).
elementoSubjetivo('desear',-3).
elementoSubjetivo('desechado',-3).
elementoSubjetivo('desempleados',-3).
elementoSubjetivo('desempleo',-3).
elementoSubjetivo('desenfrenada',-3).
elementoSubjetivo('deserciÛn',-3).
elementoSubjetivo('desertor',-3).
elementoSubjetivo('desesperaciÛn',-3).
elementoSubjetivo('desesperado',-3).
elementoSubjetivo('desesperar',-3).
elementoSubjetivo('desfavorable',-3).
elementoSubjetivo('desfavorecidas',-3).
elementoSubjetivo('desgaste',-3).
elementoSubjetivo('desglose',-3).
elementoSubjetivo('desgracia',-3).
elementoSubjetivo('deshacer',-3).
elementoSubjetivo('deshonestos',-3).
elementoSubjetivo('deshonor',-3).
elementoSubjetivo('desierto',-3).
elementoSubjetivo('desigual',-3).
elementoSubjetivo('desigualdad',-3).
elementoSubjetivo('desilusiÛn',-3).
elementoSubjetivo('desinformar',-3).
elementoSubjetivo('desinterÈs',-3).
elementoSubjetivo('desleal',-3).
elementoSubjetivo('desmoralizar',-3).
elementoSubjetivo('desmoronarse',-3).
elementoSubjetivo('desobediencia',-3).
elementoSubjetivo('desobedientes',-3).
elementoSubjetivo('desolaciÛn',-3).
elementoSubjetivo('desolado',-3).
elementoSubjetivo('desorden',-3).
elementoSubjetivo('desordenado',-3).
elementoSubjetivo('desorganizada',-3).
elementoSubjetivo('desorientado',-3).
elementoSubjetivo('despectivo',-3).
elementoSubjetivo('despedazar',-3).
elementoSubjetivo('despegue',-3).
elementoSubjetivo('desperdiciar',-3).
elementoSubjetivo('desperdicio',-3).
elementoSubjetivo('despiadado',-3).
elementoSubjetivo('despilfarro',-3).
elementoSubjetivo('desplazar',-3).
elementoSubjetivo('despreciable',-3).
elementoSubjetivo('despreciar',-3).
elementoSubjetivo('desprecio',-3).
elementoSubjetivo('desproporcionados',-3).
elementoSubjetivo('desprovisto',-3).
elementoSubjetivo('destacamento',-3).
elementoSubjetivo('desterrar',-3).
elementoSubjetivo('destierro',-3).
elementoSubjetivo('destrucciÛn',-3).
elementoSubjetivo('destructivas',-3).
elementoSubjetivo('destruir',-3).
elementoSubjetivo('desventaja',-3).
elementoSubjetivo('desventurado',-3).
elementoSubjetivo('desviaciÛn',-3).
elementoSubjetivo('desviar',-3).
elementoSubjetivo('detener',-3).
elementoSubjetivo('detest',-3).
elementoSubjetivo('detestable',-3).
elementoSubjetivo('detestar',-3).
elementoSubjetivo('detracciÛn',-3).
elementoSubjetivo('deuda',-3).
elementoSubjetivo('deudor',-3).
elementoSubjetivo('devastaciÛn',-3).
elementoSubjetivo('devastar',-3).
elementoSubjetivo('diabÛlico',-3).
elementoSubjetivo('diablo',-3).
elementoSubjetivo('diabolical',-3).
elementoSubjetivo('dictar',-3).
elementoSubjetivo('dictatorial',-3).
elementoSubjetivo('difÌcil',-3).
elementoSubjetivo('difamar',-3).
elementoSubjetivo('diferir',-3).
elementoSubjetivo('dificultad',-3).
elementoSubjetivo('dificultar',-3).
elementoSubjetivo('dilatar',-3).
elementoSubjetivo('dilema',-3).
elementoSubjetivo('diluvio',-3).
elementoSubjetivo('discordante',-3).
elementoSubjetivo('discordia',-3).
elementoSubjetivo('discrepant',-3).
elementoSubjetivo('discrimina',-3).
elementoSubjetivo('discriminaciÛn',-3).
elementoSubjetivo('discutible',-3).
elementoSubjetivo('disentimiento',-3).
elementoSubjetivo('disfraz',-3).
elementoSubjetivo('disgustado',-3).
elementoSubjetivo('disgusto',-3).
elementoSubjetivo('disidencia',-3).
elementoSubjetivo('disipaciÛn',-3).
elementoSubjetivo('disminuir',-3).
elementoSubjetivo('disoluciÛn',-3).
elementoSubjetivo('dispensability',-3).
elementoSubjetivo('dispensar',-3).
elementoSubjetivo('displease',-3).
elementoSubjetivo('disputar',-3).
elementoSubjetivo('dissatisfy',-3).
elementoSubjetivo('distanciado',-3).
elementoSubjetivo('distante',-3).
elementoSubjetivo('distracciÛn',-3).
elementoSubjetivo('distraer',-3).
elementoSubjetivo('disturb',-3).
elementoSubjetivo('disturbio',-3).
elementoSubjetivo('disturbios',-3).
elementoSubjetivo('disuasiÛn',-3).
elementoSubjetivo('diversiÛn',-3).
elementoSubjetivo('diversion',-3).
elementoSubjetivo('dividir',-3).
elementoSubjetivo('divisiÛn',-3).
elementoSubjetivo('divorcio',-3).
elementoSubjetivo('dizzy',-3).
elementoSubjetivo('doble',-3).
elementoSubjetivo('dolencia',-3).
elementoSubjetivo('dolor',-3).
elementoSubjetivo('dolor_de_cabeza',-3).
elementoSubjetivo('doloroso',-3).
elementoSubjetivo('dominaciÛn',-3).
elementoSubjetivo('dominante',-3).
elementoSubjetivo('dominar',-3).
elementoSubjetivo('dopaje',-3).
elementoSubjetivo('dormir',-3).
elementoSubjetivo('downcast',-3).
elementoSubjetivo('duda',-3).
elementoSubjetivo('dudoso',-3).
elementoSubjetivo('duelo',-3).
elementoSubjetivo('dull',-3).
elementoSubjetivo('dumb',-3).
elementoSubjetivo('dump',-3).
elementoSubjetivo('dungeon',-3).
elementoSubjetivo('dureza',-3).
elementoSubjetivo('duro',-3).
elementoSubjetivo('edge',-3).
elementoSubjetivo('egoÌsmo',-3).
elementoSubjetivo('egoÌsta',-3).
elementoSubjetivo('egoÌstas',-3).
elementoSubjetivo('ejÈrcito',-3).
elementoSubjetivo('ejecuciÛn',-3).
elementoSubjetivo('ejecucion',-3).
elementoSubjetivo('eliminaciÛn',-3).
elementoSubjetivo('eliminar',-3).
elementoSubjetivo('eludir',-3).
elementoSubjetivo('emboscada',-3).
elementoSubjetivo('embriagar',-3).
elementoSubjetivo('embrollo',-3).
elementoSubjetivo('emergencia',-3).
elementoSubjetivo('empeorar',-3).
elementoSubjetivo('empleo',-3).
elementoSubjetivo('enajenaciÛn',-3).
elementoSubjetivo('enajenar',-3).
elementoSubjetivo('encarcelar',-3).
elementoSubjetivo('encerrar',-3).
elementoSubjetivo('enclenque',-3).
elementoSubjetivo('encoger',-3).
elementoSubjetivo('endebles',-3).
elementoSubjetivo('enemigo',-3).
elementoSubjetivo('enfadado',-3).
elementoSubjetivo('enfado',-3).
elementoSubjetivo('enfermedad',-3).
elementoSubjetivo('enfermizo',-3).
elementoSubjetivo('enfermo',-3).
elementoSubjetivo('enfrentamiento',-3).
elementoSubjetivo('enfrentar',-3).
elementoSubjetivo('enfurecer',-3).
elementoSubjetivo('enfurecido',-3).
elementoSubjetivo('engaÒar',-3).
elementoSubjetivo('engaÒo',-3).
elementoSubjetivo('engaÒosas',-3).
elementoSubjetivo('engorrosos',-3).
elementoSubjetivo('engreÌdo',-3).
elementoSubjetivo('engreimiento',-3).
elementoSubjetivo('enjuiciamiento',-3).
elementoSubjetivo('enojado',-3).
elementoSubjetivo('enojo',-3).
elementoSubjetivo('enredar',-3).
elementoSubjetivo('entierro',-3).
elementoSubjetivo('entrometerse',-3).
elementoSubjetivo('entrometido',-3).
elementoSubjetivo('envidia',-3).
elementoSubjetivo('epÌteto',-3).
elementoSubjetivo('epidemia',-3).
elementoSubjetivo('equÌvoca',-3).
elementoSubjetivo('equivocar',-3).
elementoSubjetivo('erar',-3).
elementoSubjetivo('erode',-3).
elementoSubjetivo('erosiÛn',-3).
elementoSubjetivo('errÛneo',-3).
elementoSubjetivo('err',-3).
elementoSubjetivo('erradicar',-3).
elementoSubjetivo('error',-3).
elementoSubjetivo('esc·ndalo',-3).
elementoSubjetivo('escÈptico',-3).
elementoSubjetivo('escaldaduras',-3).
elementoSubjetivo('escandaloso',-3).
elementoSubjetivo('escapar',-3).
elementoSubjetivo('escaramuza',-3).
elementoSubjetivo('escasez',-3).
elementoSubjetivo('escaso',-3).
elementoSubjetivo('esclavizar',-3).
elementoSubjetivo('esclavo',-3).
elementoSubjetivo('esconder',-3).
elementoSubjetivo('escopeta',-3).
elementoSubjetivo('escorbuto',-3).
elementoSubjetivo('escoria',-3).
elementoSubjetivo('escorpiÛn',-3).
elementoSubjetivo('escr˙pulos',-3).
elementoSubjetivo('esguince',-3).
elementoSubjetivo('esotÈrico',-3).
elementoSubjetivo('espada',-3).
elementoSubjetivo('espantoso',-3).
elementoSubjetivo('esperanza',-3).
elementoSubjetivo('esperar',-3).
elementoSubjetivo('espina',-3).
elementoSubjetivo('espinoso',-3).
elementoSubjetivo('est˙pido',-3).
elementoSubjetivo('estallar',-3).
elementoSubjetivo('estancado',-3).
elementoSubjetivo('estancamiento',-3).
elementoSubjetivo('estatica',-3).
elementoSubjetivo('estiÈrcol',-3).
elementoSubjetivo('estigma',-3).
elementoSubjetivo('estrÈs',-3).
elementoSubjetivo('estrangular',-3).
elementoSubjetivo('estremecer',-3).
elementoSubjetivo('estremecerse',-3).
elementoSubjetivo('estricto',-3).
elementoSubjetivo('estridente',-3).
elementoSubjetivo('estropear',-3).
elementoSubjetivo('estruendo',-3).
elementoSubjetivo('estudio',-3).
elementoSubjetivo('estupidez',-3).
elementoSubjetivo('estupor',-3).
elementoSubjetivo('evadir',-3).
elementoSubjetivo('evasion',-3).
elementoSubjetivo('exÛtico',-3).
elementoSubjetivo('exagerar',-3).
elementoSubjetivo('examinar',-3).
elementoSubjetivo('exasperaciÛn',-3).
elementoSubjetivo('exasperar',-3).
elementoSubjetivo('excÈntricas',-3).
elementoSubjetivo('excentricidad',-3).
elementoSubjetivo('excepciÛn',-3).
elementoSubjetivo('excesivo',-3).
elementoSubjetivo('exceso',-3).
elementoSubjetivo('excluir',-3).
elementoSubjetivo('exclusiÛn',-3).
elementoSubjetivo('excomuniÛn',-3).
elementoSubjetivo('excusa',-3).
elementoSubjetivo('execute',-3).
elementoSubjetivo('exento',-3).
elementoSubjetivo('exilio',-3).
elementoSubjetivo('expediente',-3).
elementoSubjetivo('expiatorio',-3).
elementoSubjetivo('explosiÛn',-3).
elementoSubjetivo('explosivo',-3).
elementoSubjetivo('explotar',-3).
elementoSubjetivo('exponer',-3).
elementoSubjetivo('expulsar',-3).
elementoSubjetivo('exterminar',-3).
elementoSubjetivo('exterminio',-3).
elementoSubjetivo('extinto',-3).
elementoSubjetivo('extradiciÛn',-3).
elementoSubjetivo('extravagantes',-3).
elementoSubjetivo('fÈtido',-3).
elementoSubjetivo('fabricaciÛn',-3).
elementoSubjetivo('fabricar',-3).
elementoSubjetivo('fallar',-3).
elementoSubjetivo('fallecimiento',-3).
elementoSubjetivo('fallo',-3).
elementoSubjetivo('falseamiento',-3).
elementoSubjetivo('falsear',-3).
elementoSubjetivo('falsedad',-3).
elementoSubjetivo('falso ',-3).
elementoSubjetivo('falso',-3).
elementoSubjetivo('falta',-3).
elementoSubjetivo('faltar',-3).
elementoSubjetivo('falter',-3).
elementoSubjetivo('famÈlico',-3).
elementoSubjetivo('fan·tico',-3).
elementoSubjetivo('faneca',-3).
elementoSubjetivo('fangosos',-3).
elementoSubjetivo('farsa',-3).
elementoSubjetivo('fascista',-3).
elementoSubjetivo('fastidiar',-3).
elementoSubjetivo('fatal',-3).
elementoSubjetivo('fatalista',-3).
elementoSubjetivo('fatiga',-3).
elementoSubjetivo('fatigado',-3).
elementoSubjetivo('fatigoso',-3).
elementoSubjetivo('febril',-3).
elementoSubjetivo('fed',-3).
elementoSubjetivo('feo',-3).
elementoSubjetivo('feroces',-3).
elementoSubjetivo('ferocidad',-3).
elementoSubjetivo('feroz',-3).
elementoSubjetivo('feudal',-3).
elementoSubjetivo('feudo',-3).
elementoSubjetivo('fiabilidad',-3).
elementoSubjetivo('fiables',-3).
elementoSubjetivo('fiasco',-3).
elementoSubjetivo('fidget',-3).
elementoSubjetivo('fiebre',-3).
elementoSubjetivo('fiend',-3).
elementoSubjetivo('fingir',-3).
elementoSubjetivo('finta',-3).
elementoSubjetivo('flagrante',-3).
elementoSubjetivo('flecha',-3).
elementoSubjetivo('flemÛn',-3).
elementoSubjetivo('fobia',-3).
elementoSubjetivo('foe',-3).
elementoSubjetivo('fofo',-3).
elementoSubjetivo('follÛn',-3).
elementoSubjetivo('forjar',-3).
elementoSubjetivo('formidable',-3).
elementoSubjetivo('fr·gil',-3).
elementoSubjetivo('frÌgido',-3).
elementoSubjetivo('frÌo',-3).
elementoSubjetivo('frÌvolo',-3).
elementoSubjetivo('fracaso',-3).
elementoSubjetivo('fractura',-3).
elementoSubjetivo('frantic',-3).
elementoSubjetivo('fraude',-3).
elementoSubjetivo('fraudulenta',-3).
elementoSubjetivo('freak',-3).
elementoSubjetivo('frenÈticamente',-3).
elementoSubjetivo('frente',-3).
elementoSubjetivo('fruncir',-3).
elementoSubjetivo('frustraciÛn',-3).
elementoSubjetivo('frustrado',-3).
elementoSubjetivo('frustrar',-3).
elementoSubjetivo('fuego',-3). %sacarlo?
elementoSubjetivo('fuerza',-3). %sacarlo?
elementoSubjetivo('fuga',-3).
elementoSubjetivo('fugarse',-3).
elementoSubjetivo('fugaz',-3).
elementoSubjetivo('fundador',-3).
elementoSubjetivo('funeral',-3).
elementoSubjetivo('furcia',-3).
elementoSubjetivo('furia',-3).
elementoSubjetivo('furioso',-3).
elementoSubjetivo('fusil',-3).
elementoSubjetivo('gÈlido',-3).
elementoSubjetivo('gÈrmenes',-3).
elementoSubjetivo('gangrena',-3).
elementoSubjetivo('gasto',-3).
elementoSubjetivo('gemir',-3).
elementoSubjetivo('gestiÛn',-3).
elementoSubjetivo('ghetto',-3).
elementoSubjetivo('girar',-3).
elementoSubjetivo('glare',-3).
elementoSubjetivo('golpe',-3).
elementoSubjetivo('golpear',-3).
elementoSubjetivo('gordo',-3).
elementoSubjetivo('gozar',-3).
elementoSubjetivo('granada',-3).
elementoSubjetivo('grasa',-3).
elementoSubjetivo('gratuito',-3).
elementoSubjetivo('grave',-3).
elementoSubjetivo('gravoso',-3).
elementoSubjetivo('gripe',-3).
elementoSubjetivo('grito',-3).
elementoSubjetivo('grosero',-3).
elementoSubjetivo('grotesco',-3).
elementoSubjetivo('gruÒido',-3).
elementoSubjetivo('gruÒir',-3).
elementoSubjetivo('grueso',-3).
elementoSubjetivo('guerra',-3).
elementoSubjetivo('guerrero',-3).
elementoSubjetivo('guillotina',-3).
elementoSubjetivo('guise',-3).
elementoSubjetivo('gusano',-3).
elementoSubjetivo('hacker',-3).
elementoSubjetivo('hambre',-3).
elementoSubjetivo('hambriento',-3).
elementoSubjetivo('hambruna',-3).
elementoSubjetivo('handicap',-3).
elementoSubjetivo('harras',-3).
elementoSubjetivo('harto',-3).
elementoSubjetivo('hastÌo',-3).
elementoSubjetivo('hedonista',-3).
elementoSubjetivo('hedor',-3).
elementoSubjetivo('herida',-3).
elementoSubjetivo('heridas',-3).
elementoSubjetivo('herido',-3).
elementoSubjetivo('herir',-3).
elementoSubjetivo('heroÌna',-3).
elementoSubjetivo('hierro',-3).
elementoSubjetivo('hipÛcrita',-3).
elementoSubjetivo('hipocresÌa',-3).
elementoSubjetivo('hiriente',-3).
elementoSubjetivo('histÈrico',-3).
elementoSubjetivo('histeria',-3).
elementoSubjetivo('holgaz·n',-3).
elementoSubjetivo('homicida',-3).
elementoSubjetivo('homicidio',-3).
elementoSubjetivo('hongo',-3).
elementoSubjetivo('horde',-3).
elementoSubjetivo('horrible',-3).
elementoSubjetivo('horror',-3).
elementoSubjetivo('hosco',-3).
elementoSubjetivo('hospital',-3).
elementoSubjetivo('hostil',-3).
elementoSubjetivo('hostilidad',-3).
elementoSubjetivo('huelga',-3).
elementoSubjetivo('huir',-3).
elementoSubjetivo('humilde',-3).
elementoSubjetivo('humillaciÛn',-3).
elementoSubjetivo('humillar',-3).
elementoSubjetivo('hundimiento',-3).
elementoSubjetivo('hundir',-3).
elementoSubjetivo('hurac·n',-3).
elementoSubjetivo('idiota',-3).
elementoSubjetivo('iglesia',-3).
elementoSubjetivo('ignorancia',-3).
elementoSubjetivo('ignorar',-3).
elementoSubjetivo('ilÌcita',-3).
elementoSubjetivo('ilÛgico',-3).
elementoSubjetivo('ilegal',-3).
elementoSubjetivo('ilegalidad',-3).
elementoSubjetivo('impaciencia',-3).
elementoSubjetivo('impaciente',-3).
elementoSubjetivo('impar',-3).
elementoSubjetivo('impasible',-3).
elementoSubjetivo('impedimento',-3).
elementoSubjetivo('imperfecta',-3).
elementoSubjetivo('impersonal',-3).
elementoSubjetivo('impetuoso',-3).
elementoSubjetivo('implacable',-3).
elementoSubjetivo('implicar',-3).
elementoSubjetivo('implorar',-3).
elementoSubjetivo('imponer',-3).
elementoSubjetivo('impopulares',-3).
elementoSubjetivo('importancia',-3).
elementoSubjetivo('impotencia',-3).
elementoSubjetivo('impotente',-3).
elementoSubjetivo('imprecisiÛn',-3).
elementoSubjetivo('imprevisible',-3).
elementoSubjetivo('imprevistos',-3).
elementoSubjetivo('improcedentes',-3).
elementoSubjetivo('impropios',-3).
elementoSubjetivo('imprudencia',-3).
elementoSubjetivo('imprudente',-3).
elementoSubjetivo('impuesto',-3).
elementoSubjetivo('impulsivo',-3).
elementoSubjetivo('impureza',-3).
elementoSubjetivo('impuros',-3).
elementoSubjetivo('in˙til',-3).
elementoSubjetivo('inaccesible',-3).
elementoSubjetivo('inadaptaciÛn',-3).
elementoSubjetivo('inadaptados',-3).
elementoSubjetivo('inadvertido',-3).
elementoSubjetivo('inane',-3).
elementoSubjetivo('inaniciÛn',-3).
elementoSubjetivo('incÛmodo',-3).
elementoSubjetivo('incalificable',-3).
elementoSubjetivo('incapacidad',-3).
elementoSubjetivo('incapaz',-3).
elementoSubjetivo('incesante',-3).
elementoSubjetivo('incivil',-3).
elementoSubjetivo('incluso',-3).
elementoSubjetivo('incomodidad',-3).
elementoSubjetivo('incompatibilidad',-3).
elementoSubjetivo('incompatible',-3).
elementoSubjetivo('incompetencia',-3).
elementoSubjetivo('incompetente',-3).
elementoSubjetivo('incomprensiÛn',-3).
elementoSubjetivo('inconsistencia',-3).
elementoSubjetivo('inconveniente',-3).
elementoSubjetivo('incordio',-3).
elementoSubjetivo('incorrecto',-3).
elementoSubjetivo('increÌble',-3).
elementoSubjetivo('incredulidad',-3).
elementoSubjetivo('increible',-3).
elementoSubjetivo('incumplido',-3).
elementoSubjetivo('incumplimiento',-3).
elementoSubjetivo('incurable',-3).
elementoSubjetivo('indebida',-3).
elementoSubjetivo('indebido',-3).
elementoSubjetivo('indecente',-3).
elementoSubjetivo('indecisiÛn',-3).
elementoSubjetivo('indeciso',-3).
elementoSubjetivo('indefenso',-3).
elementoSubjetivo('indefinido',-3).
elementoSubjetivo('independientemente',-3).
elementoSubjetivo('indeterminable',-3).
elementoSubjetivo('indeterminado',-3).
elementoSubjetivo('indiferente',-3).
elementoSubjetivo('indifference',-3).
elementoSubjetivo('indigentes',-3).
elementoSubjetivo('indignaciÛn',-3).
elementoSubjetivo('indignar',-3).
elementoSubjetivo('indisciplinado',-3).
elementoSubjetivo('indolentes',-3).
elementoSubjetivo('inducir',-3).
elementoSubjetivo('indulge',-3).
elementoSubjetivo('ineffectualness',-3).
elementoSubjetivo('ineficacia',-3).
elementoSubjetivo('ineficaz',-3).
elementoSubjetivo('ineficiencia',-3).
elementoSubjetivo('inesperadamente',-3).
elementoSubjetivo('inestabilidad',-3).
elementoSubjetivo('inestable',-3).
elementoSubjetivo('inevitable',-3).
elementoSubjetivo('inexacto',-3).
elementoSubjetivo('inexperto',-3).
elementoSubjetivo('inexplicable',-3).
elementoSubjetivo('infamous',-3).
elementoSubjetivo('infantil',-3).
elementoSubjetivo('infecciÛn',-3).
elementoSubjetivo('infectar',-3).
elementoSubjetivo('infelicidad',-3).
elementoSubjetivo('infeliz',-3).
elementoSubjetivo('inferior',-3).
elementoSubjetivo('inferioridad',-3).
elementoSubjetivo('infestar',-3).
elementoSubjetivo('infiel',-3).
elementoSubjetivo('infierno',-3).
elementoSubjetivo('infiltraciÛn',-3).
elementoSubjetivo('inflaciÛn',-3).
elementoSubjetivo('inflamar',-3).
elementoSubjetivo('infligir',-3).
elementoSubjetivo('infracciÛn',-3).
elementoSubjetivo('infructuoso',-3).
elementoSubjetivo('ingratitud',-3).
elementoSubjetivo('inhibiciÛn',-3).
elementoSubjetivo('inhibir',-3).
elementoSubjetivo('inhumano',-3).
elementoSubjetivo('injuriar',-3).
elementoSubjetivo('injustificada',-3).
elementoSubjetivo('injusto',-3).
elementoSubjetivo('inmÛvil',-3).
elementoSubjetivo('inmaduro',-3).
elementoSubjetivo('inmoral',-3).
elementoSubjetivo('inmoralidad',-3).
elementoSubjetivo('inmovilidad',-3).
elementoSubjetivo('inmuebles',-3).
elementoSubjetivo('innecesario',-3).
elementoSubjetivo('innoble',-3).
elementoSubjetivo('inoportuno',-3).
elementoSubjetivo('inquietante',-3).
elementoSubjetivo('inquieto',-3).
elementoSubjetivo('inquietud',-3).
elementoSubjetivo('insalubres',-3).
elementoSubjetivo('insano',-3).
elementoSubjetivo('insatisfacciÛn',-3).
elementoSubjetivo('insatisfactorio',-3).
elementoSubjetivo('insecto',-3).
elementoSubjetivo('inseguridad',-3).
elementoSubjetivo('inseguro',-3).
elementoSubjetivo('insensible',-3).
elementoSubjetivo('insidioso',-3).
elementoSubjetivo('insignificante',-3).
elementoSubjetivo('insinuar',-3).
elementoSubjetivo('insolencia',-3).
elementoSubjetivo('insolente',-3).
elementoSubjetivo('insoportable',-3).
elementoSubjetivo('insuficiencia',-3).
elementoSubjetivo('insuficiente',-3).
elementoSubjetivo('insulto',-3).
elementoSubjetivo('inteligencia',-3).
elementoSubjetivo('interceptaciÛn',-3).
elementoSubjetivo('interferencia',-3).
elementoSubjetivo('interferir',-3).
elementoSubjetivo('interrupciÛn',-3).
elementoSubjetivo('intervenciÛn',-3). %si es sinÛnimo de operaciÛn no es negativo
elementoSubjetivo('intimidante',-3).
elementoSubjetivo('intimidar',-3).
elementoSubjetivo('intolerable',-3).
elementoSubjetivo('intrusiÛn',-3).
elementoSubjetivo('intruso',-3).
elementoSubjetivo('inundaciÛn',-3).
elementoSubjetivo('inundar',-3).
elementoSubjetivo('inutilidad',-3).
elementoSubjetivo('invadir',-3).
elementoSubjetivo('invasiÛn',-3).
elementoSubjetivo('invasor',-3).
elementoSubjetivo('invisible',-3).
elementoSubjetivo('involuntarias',-3).
elementoSubjetivo('irÛnica',-3).
elementoSubjetivo('irÛnico',-3).
elementoSubjetivo('ira',-3).
elementoSubjetivo('ironÌa',-3).
elementoSubjetivo('irracional',-3).
elementoSubjetivo('irregular',-3).
elementoSubjetivo('irregularidad',-3).
elementoSubjetivo('irresponsabilidad',-3).
elementoSubjetivo('irresponsable',-3).
elementoSubjetivo('irrisiÛn',-3).
elementoSubjetivo('irritable',-3).
elementoSubjetivo('irritaciÛn',-3).
elementoSubjetivo('irritar',-3).
elementoSubjetivo('jactancioso',-3).
elementoSubjetivo('jactarse',-3).
elementoSubjetivo('jagged',-3).
elementoSubjetivo('jaqueca',-3).
elementoSubjetivo('jar',-3).
elementoSubjetivo('jerk',-3).
elementoSubjetivo('jittery',-3).
elementoSubjetivo('joven',-3).
elementoSubjetivo('jubilar',-3).
elementoSubjetivo('judicial',-3).
elementoSubjetivo('jurar',-3).
elementoSubjetivo('l·nguido',-3).
elementoSubjetivo('l·stima',-3).
elementoSubjetivo('l·tigo',-3).
elementoSubjetivo('lÌmite',-3).
elementoSubjetivo('lÛbrego',-3).
elementoSubjetivo('laboriosamente',-3).
elementoSubjetivo('ladrÛn',-3).
elementoSubjetivo('laicos',-3).
elementoSubjetivo('lament',-3).
elementoSubjetivo('lamentable',-3).
elementoSubjetivo('languidecer',-3).
elementoSubjetivo('lento',-3).
elementoSubjetivo('lepra',-3).
elementoSubjetivo('lesiÛn',-3).
elementoSubjetivo('liar',-3).
elementoSubjetivo('lidiar',-3).
elementoSubjetivo('ligero',-3).
elementoSubjetivo('limitaciÛn',-3).
elementoSubjetivo('limitar',-3).
elementoSubjetivo('limo',-3).
elementoSubjetivo('limp',-3).
elementoSubjetivo('liquidaciÛn',-3).
elementoSubjetivo('liquidar',-3).
elementoSubjetivo('litigantes',-3).
elementoSubjetivo('litigio',-3).
elementoSubjetivo('llevar',-3).
elementoSubjetivo('llorar',-3).
elementoSubjetivo('lloriqueo',-3).
elementoSubjetivo('lluvia',-3).
elementoSubjetivo('loco',-3).
elementoSubjetivo('locura',-3).
elementoSubjetivo('lucha',-3).
elementoSubjetivo('luchar',-3).
elementoSubjetivo('lun·tico',-3).
elementoSubjetivo('m·quina',-3).
elementoSubjetivo('mal',-3).
elementoSubjetivo('malaria',-3).
elementoSubjetivo('maldad',-3).
elementoSubjetivo('maldito',-3).
elementoSubjetivo('maleducado',-3).
elementoSubjetivo('malestar',-3).
elementoSubjetivo('malezas',-3).
elementoSubjetivo('malicia',-3).
elementoSubjetivo('malicioso',-3).
elementoSubjetivo('maligno',-3).
elementoSubjetivo('malo',-3).
elementoSubjetivo('maltrato',-3).
elementoSubjetivo('malvado',-3).
elementoSubjetivo('manÌa',-3).
elementoSubjetivo('manÌaco',-3).
elementoSubjetivo('mancha',-3).
elementoSubjetivo('mandamiento',-3).
elementoSubjetivo('manejar',-3).
elementoSubjetivo('manipulaciÛn',-3).
elementoSubjetivo('manipular',-3).
elementoSubjetivo('manosear',-3).
elementoSubjetivo('mantener',-3). % mantenerse NO
elementoSubjetivo('marca',-3).
elementoSubjetivo('mareado',-3).
elementoSubjetivo('marginal',-3).
elementoSubjetivo('masacre',-3).
elementoSubjetivo('matanza',-3).
elementoSubjetivo('matar',-3).
elementoSubjetivo('materia',-3).
elementoSubjetivo('medio',-3).
elementoSubjetivo('mediocre',-3).
elementoSubjetivo('melancolÌa',-3).
elementoSubjetivo('melodram·tico',-3).
elementoSubjetivo('menace',-3).
elementoSubjetivo('mendigo',-3).
elementoSubjetivo('menoscabarÌa',-3).
elementoSubjetivo('menospreciar',-3).
elementoSubjetivo('menosprecio',-3).
elementoSubjetivo('mentir',-3).
elementoSubjetivo('mentira',-3).
elementoSubjetivo('mentiroso',-3).
elementoSubjetivo('merodear',-3).
elementoSubjetivo('mess',-3).
elementoSubjetivo('miedo',-3).
elementoSubjetivo('miedoso',-3).
elementoSubjetivo('mina',-3).
elementoSubjetivo('miope',-3).
elementoSubjetivo('mischief',-3).
elementoSubjetivo('miserable',-3).
elementoSubjetivo('miseria',-3).
elementoSubjetivo('misery',-3).
elementoSubjetivo('mishandle',-3).
elementoSubjetivo('mishap',-3).
elementoSubjetivo('misiles',-3).
elementoSubjetivo('misunderstood',-3).
elementoSubjetivo('mito',-3).
elementoSubjetivo('mix',-3).
elementoSubjetivo('mob',-3).
elementoSubjetivo('modelo',-3).
elementoSubjetivo('moho',-3).
elementoSubjetivo('molestar',-3).
elementoSubjetivo('molestia',-3).
elementoSubjetivo('molesto',-3).
elementoSubjetivo('monÛtono',-3).
elementoSubjetivo('monja',-3).
elementoSubjetivo('monotonÌa',-3).
elementoSubjetivo('monster',-3).
elementoSubjetivo('monstruoso',-3).
elementoSubjetivo('moody',-3).
elementoSubjetivo('mordedura',-3).
elementoSubjetivo('moretÛn',-3).
elementoSubjetivo('morgue',-3).
elementoSubjetivo('morir',-3).
elementoSubjetivo('mortal',-3).
elementoSubjetivo('mortificar',-3).
elementoSubjetivo('mosquito',-3).
elementoSubjetivo('mostrar',-3).
elementoSubjetivo('motley',-3).
elementoSubjetivo('mucosidad',-3).
elementoSubjetivo('muerte',-3).
elementoSubjetivo('muerto',-3).
elementoSubjetivo('mugre',-3).
elementoSubjetivo('muleta',-3).
elementoSubjetivo('multa',-3).
elementoSubjetivo('mundano',-3).
elementoSubjetivo('musaraÒa',-3).
elementoSubjetivo('mutaciÛn',-3).
elementoSubjetivo('mutilar',-3).
elementoSubjetivo('naive',-3).
elementoSubjetivo('narcÛtico',-3).
elementoSubjetivo('nasty',-3).
elementoSubjetivo('naufragio',-3).
elementoSubjetivo('navidad',-3).
elementoSubjetivo('nebuloso',-3).
elementoSubjetivo('necesidad',-3).
elementoSubjetivo('necesitar',-3).
elementoSubjetivo('negaciÛn',-3).
elementoSubjetivo('negar',-3).
elementoSubjetivo('negativo',-3).
elementoSubjetivo('negligencia',-3).
elementoSubjetivo('negligentes',-3).
elementoSubjetivo('negro',-3).
elementoSubjetivo('nerviosismo',-3).
elementoSubjetivo('nervioso',-3).
elementoSubjetivo('neurÛtico',-3).
elementoSubjetivo('neutralizaciÛn',-3).
elementoSubjetivo('neutralizar',-3).
elementoSubjetivo('nocivo',-3).
elementoSubjetivo('notorio',-3).
elementoSubjetivo('nublado',-3).
elementoSubjetivo('nudo',-3).
elementoSubjetivo('obedecer',-3).
elementoSubjetivo('obesidad',-3).
elementoSubjetivo('objeciÛn',-3).
elementoSubjetivo('objeto',-3).
elementoSubjetivo('oblicuo',-3).
elementoSubjetivo('obligar',-3).
elementoSubjetivo('obsceno',-3).
elementoSubjetivo('obsesiÛn',-3).
elementoSubjetivo('obsoleto',-3).
elementoSubjetivo('obst·culo',-3).
elementoSubjetivo('obstaculiza',-3).
elementoSubjetivo('obstaculizar',-3).
elementoSubjetivo('obstinadamente',-3).
elementoSubjetivo('obstinado',-3).
elementoSubjetivo('obtener',-3).
elementoSubjetivo('ociosidad',-3).
elementoSubjetivo('ocultar',-3).
elementoSubjetivo('odiar',-3).
elementoSubjetivo('odio',-3).
elementoSubjetivo('odioso',-3).
elementoSubjetivo('ofender',-3).
elementoSubjetivo('ofensivo',-3).
elementoSubjetivo('ofensores',-3).
elementoSubjetivo('oferta',-3).
elementoSubjetivo('olvido',-3).
elementoSubjetivo('omisiÛn',-3).
elementoSubjetivo('omitir',-3).
elementoSubjetivo('oponer',-3).
elementoSubjetivo('oposiciÛn',-3).
elementoSubjetivo('opresiÛn',-3).
elementoSubjetivo('opresivo',-3).
elementoSubjetivo('oprimir',-3).
elementoSubjetivo('orden',-3).
elementoSubjetivo('ordenar',-3).
elementoSubjetivo('orfandad',-3).
elementoSubjetivo('orina',-3).
elementoSubjetivo('oscurecer',-3).
elementoSubjetivo('oscuridad',-3).
elementoSubjetivo('oscuro',-3).
elementoSubjetivo('otoÒo',-3).
elementoSubjetivo('oxidado',-3).
elementoSubjetivo('p·nico',-3).
elementoSubjetivo('pÈrdida',-3).
elementoSubjetivo('pacotilla',-3).
elementoSubjetivo('pandemonium',-3).
elementoSubjetivo('pantano',-3).
elementoSubjetivo('par·lisis',-3).
elementoSubjetivo('par·sito',-3).
elementoSubjetivo('paralizar',-3).
elementoSubjetivo('paranoico',-3).
elementoSubjetivo('particiÛn',-3).
elementoSubjetivo('particular',-3).
elementoSubjetivo('patÈtico',-3).
elementoSubjetivo('pecado',-3).
elementoSubjetivo('pecaminoso',-3).
elementoSubjetivo('peculiar',-3).
elementoSubjetivo('pelea',-3).
elementoSubjetivo('peleador',-3).
elementoSubjetivo('pelear',-3).
elementoSubjetivo('peligro',-3).
elementoSubjetivo('peligroso',-3).
elementoSubjetivo('pellizco',-3).
elementoSubjetivo('pena',-3).
elementoSubjetivo('penal',-3).
elementoSubjetivo('pendenciero',-3).
elementoSubjetivo('penetraciÛn',-3).
elementoSubjetivo('penetrar',-3).
elementoSubjetivo('penosamente',-3).
elementoSubjetivo('penoso',-3).
elementoSubjetivo('peor',-3).
elementoSubjetivo('perdedor',-3).
elementoSubjetivo('perder',-3).
elementoSubjetivo('perdido',-3).
elementoSubjetivo('perdigÛn',-3).
elementoSubjetivo('perecer',-3).
elementoSubjetivo('perezosamente',-3).
elementoSubjetivo('perezoso',-3).
elementoSubjetivo('peril',-3).
elementoSubjetivo('perjudicar',-3).
elementoSubjetivo('perjudiciales',-3).
elementoSubjetivo('perjuicio',-3).
elementoSubjetivo('perplejidad',-3).
elementoSubjetivo('perplejidades',-3).
elementoSubjetivo('perplex',-3).
elementoSubjetivo('perra',-3).
elementoSubjetivo('persecuciÛn',-3).
elementoSubjetivo('perseguir',-3).
elementoSubjetivo('perturbaciÛn',-3).
elementoSubjetivo('perturbar',-3).
elementoSubjetivo('perverso',-3).
elementoSubjetivo('pervert',-3).
elementoSubjetivo('pervertido',-3).
elementoSubjetivo('pesadilla',-3).
elementoSubjetivo('pesar',-3).
elementoSubjetivo('pesaroso',-3).
elementoSubjetivo('pesimismo',-3).
elementoSubjetivo('pesimista',-3).
elementoSubjetivo('peso',-3).
elementoSubjetivo('peste',-3).
elementoSubjetivo('piedad',-3).
elementoSubjetivo('piedra',-3).
elementoSubjetivo('pieza',-3).
elementoSubjetivo('pinchazo',-3).
elementoSubjetivo('piojo',-3).
elementoSubjetivo('piojos',-3).
elementoSubjetivo('piso',-3).
elementoSubjetivo('pisotear',-3).
elementoSubjetivo('pistola',-3).
elementoSubjetivo('pistoleros',-3).
elementoSubjetivo('pitÛn',-3).
elementoSubjetivo('plaga',-3).
elementoSubjetivo('platija',-3).
elementoSubjetivo('pleito',-3).
elementoSubjetivo('plomo',-3).
elementoSubjetivo('pobre',-3).
elementoSubjetivo('pobreza',-3).
elementoSubjetivo('poco',-3).
elementoSubjetivo('podrido',-3).
elementoSubjetivo('podrir',-3).
elementoSubjetivo('pomposo',-3).
elementoSubjetivo('ponzoÒa',-3).
elementoSubjetivo('porquerÌa',-3).
elementoSubjetivo('portar',-3).
elementoSubjetivo('prÛfugo',-3).
elementoSubjetivo('precaria',-3).
elementoSubjetivo('precipicio',-3).
elementoSubjetivo('precipitar',-3).
elementoSubjetivo('predeterminado',-3).
elementoSubjetivo('pregunta',-3).
elementoSubjetivo('preocupaciÛn',-3).
elementoSubjetivo('preocupar',-3).
elementoSubjetivo('preparar',-3).
elementoSubjetivo('presentimiento',-3).
elementoSubjetivo('presiÛn',-3).
elementoSubjetivo('presuntuoso',-3).
elementoSubjetivo('pretencioso',-3).
elementoSubjetivo('pretensiÛn',-3).
elementoSubjetivo('prevenciÛn',-3).
elementoSubjetivo('primitivo',-3).
elementoSubjetivo('principiante',-3).
elementoSubjetivo('prisiÛn',-3).
elementoSubjetivo('prision',-3).
elementoSubjetivo('prisionero',-3).
elementoSubjetivo('privaciÛn',-3).
elementoSubjetivo('problema',-3).
elementoSubjetivo('prohibiciÛn',-3).
elementoSubjetivo('prohibir',-3).
elementoSubjetivo('prohibitivas',-3).
elementoSubjetivo('pronunciaciÛn',-3).
elementoSubjetivo('propaganda',-3).
elementoSubjetivo('protestar',-3).
elementoSubjetivo('provocaciÛn',-3).
elementoSubjetivo('provocar',-3).
elementoSubjetivo('puÒo',-3).
elementoSubjetivo('pulsador',-3).
elementoSubjetivo('puntapiÈ',-3).
elementoSubjetivo('pus',-3).
elementoSubjetivo('pusil·nime',-3).
elementoSubjetivo('puta',-3).
elementoSubjetivo('putrefacto',-3).
elementoSubjetivo('qualm',-3).
elementoSubjetivo('quebradizos',-3).
elementoSubjetivo('quebrar',-3).
elementoSubjetivo('queer',-3).
elementoSubjetivo('queja',-3).
elementoSubjetivo('quemadura',-3).
elementoSubjetivo('quemaduras',-3).
elementoSubjetivo('queroseno',-3).
elementoSubjetivo('quisquilloso',-3).
elementoSubjetivo('quitter',-3).
elementoSubjetivo('quo',-3).
elementoSubjetivo('rÈgimen',-3).
elementoSubjetivo('rÌgido',-3).
elementoSubjetivo('raÌz',-3).
elementoSubjetivo('rabia',-3).
elementoSubjetivo('raciÛn',-3).
elementoSubjetivo('radical',-3).
elementoSubjetivo('rage',-3).
elementoSubjetivo('raid',-3).
elementoSubjetivo('rancio',-3).
elementoSubjetivo('rapto',-3).
elementoSubjetivo('rascal',-3).
elementoSubjetivo('rasgados',-3).
elementoSubjetivo('rash',-3).
elementoSubjetivo('rastrear',-3).
elementoSubjetivo('rat',-3).
elementoSubjetivo('rata',-3).
elementoSubjetivo('ratero',-3).
elementoSubjetivo('rayo',-3).
elementoSubjetivo('reacciÛn',-3).
elementoSubjetivo('reaccionarias',-3).
elementoSubjetivo('reactivo',-3).
elementoSubjetivo('realismo',-3).
elementoSubjetivo('rebel',-3).
elementoSubjetivo('rebelde',-3).
elementoSubjetivo('rebeliÛn',-3).
elementoSubjetivo('rebelion',-3).
elementoSubjetivo('rebut',-3).
elementoSubjetivo('recaer',-3).
elementoSubjetivo('recalcitrantes',-3).
elementoSubjetivo('recesiÛn',-3).
elementoSubjetivo('receso',-3).
elementoSubjetivo('rechazado',-3).
elementoSubjetivo('recuadro',-3).
elementoSubjetivo('reducir',-3).
elementoSubjetivo('redundancia',-3).
elementoSubjetivo('redundante',-3).
elementoSubjetivo('refriega',-3).
elementoSubjetivo('refugiado',-3).
elementoSubjetivo('refutar',-3).
elementoSubjetivo('regaÒar',-3).
elementoSubjetivo('regresiÛn',-3).
elementoSubjetivo('rehÈn',-3).
elementoSubjetivo('rel·mpago',-3).
elementoSubjetivo('remordimiento',-3).
elementoSubjetivo('rencor',-3).
elementoSubjetivo('rencoroso',-3).
elementoSubjetivo('rentable',-3).
elementoSubjetivo('renuncia',-3).
elementoSubjetivo('renunciar',-3).
elementoSubjetivo('reparto',-3).
elementoSubjetivo('reprensiÛn',-3).
elementoSubjetivo('represalias',-3).
elementoSubjetivo('represiÛn',-3).
elementoSubjetivo('reprimir',-3).
elementoSubjetivo('reprochar',-3).
elementoSubjetivo('reptil',-3).
elementoSubjetivo('repugnante',-3).
elementoSubjetivo('repulse',-3).
elementoSubjetivo('repulsivo',-3).
elementoSubjetivo('resentido',-3).
elementoSubjetivo('resentir',-3).
elementoSubjetivo('resentirse',-3).
elementoSubjetivo('residuos',-3).
elementoSubjetivo('resistencia',-3).
elementoSubjetivo('resistir',-3).
elementoSubjetivo('restar',-3).
elementoSubjetivo('restricciÛn',-3).
elementoSubjetivo('restringir',-3).
elementoSubjetivo('retard',-3).
elementoSubjetivo('retardo',-3).
elementoSubjetivo('retener',-3).
elementoSubjetivo('retirada',-3).
elementoSubjetivo('reto',-3).
elementoSubjetivo('retrasado',-3).
elementoSubjetivo('retrasar',-3).
elementoSubjetivo('retraso',-3).
elementoSubjetivo('retreat',-3).
elementoSubjetivo('retroceder',-3).
elementoSubjetivo('retroceso',-3).
elementoSubjetivo('revÛlver',-3).
elementoSubjetivo('revenge',-3).
elementoSubjetivo('revisiÛn',-3).
elementoSubjetivo('revocar',-3).
elementoSubjetivo('revolcarse',-3).
elementoSubjetivo('revoluciÛn',-3).
elementoSubjetivo('revolucionario',-3).
elementoSubjetivo('revuelta',-3).
elementoSubjetivo('rezagado',-3).
elementoSubjetivo('rezongar',-3).
elementoSubjetivo('riÒa',-3).
elementoSubjetivo('ridÌculo',-3).
elementoSubjetivo('rifle',-3).
elementoSubjetivo('rigor',-3).
elementoSubjetivo('riguroso',-3).
elementoSubjetivo('rival',-3).
elementoSubjetivo('rivalidad',-3).
elementoSubjetivo('roÒa',-3).
elementoSubjetivo('robar',-3).
elementoSubjetivo('robo',-3).
elementoSubjetivo('rogar',-3).
elementoSubjetivo('romper',-3).
elementoSubjetivo('ronquido',-3).
elementoSubjetivo('roto',-3).
elementoSubjetivo('rotonda',-3).
elementoSubjetivo('rozar',-3).
elementoSubjetivo('rude',-3).
elementoSubjetivo('rufi·n',-3).
elementoSubjetivo('rugosidad',-3).
elementoSubjetivo('ruido',-3).
elementoSubjetivo('ruidoso',-3).
elementoSubjetivo('ruina',-3).
elementoSubjetivo('ruinosa',-3).
elementoSubjetivo('rumor',-3).
elementoSubjetivo('ruptura',-3).
elementoSubjetivo('s·bana',-3).
elementoSubjetivo('sÌfilis',-3).
elementoSubjetivo('sÌntoma',-3).
elementoSubjetivo('s˙plica',-3).
elementoSubjetivo('sabotaje',-3).
elementoSubjetivo('salvedad',-3).
elementoSubjetivo('sancionar',-3).
elementoSubjetivo('sangrÌa',-3).
elementoSubjetivo('sangriento',-3).
elementoSubjetivo('sanguinario',-3).
elementoSubjetivo('santo',-3).
elementoSubjetivo('sarampiÛn',-3).
elementoSubjetivo('sarcasmo',-3).
elementoSubjetivo('sarmiento',-3).
elementoSubjetivo('satisfacer',-3).
elementoSubjetivo('seÒuelo',-3).
elementoSubjetivo('secar',-3).
elementoSubjetivo('secesiÛn',-3).
elementoSubjetivo('secret',-3).
elementoSubjetivo('secreto',-3).
elementoSubjetivo('secuestrar',-3).
elementoSubjetivo('sed',-3).
elementoSubjetivo('sedentario',-3).
elementoSubjetivo('seethe',-3).
elementoSubjetivo('segregacion',-3).
elementoSubjetivo('selecciÛn',-3).
elementoSubjetivo('senil',-3).
elementoSubjetivo('sensible',-3).
elementoSubjetivo('sentencia',-3).
elementoSubjetivo('sequÌa',-3).
elementoSubjetivo('serio',-3).
elementoSubjetivo('serpiente',-3).
elementoSubjetivo('servicio',-3).
elementoSubjetivo('servidumbre',-3).
elementoSubjetivo('servir',-3).
elementoSubjetivo('severidad',-3).
elementoSubjetivo('silvestres',-3).
elementoSubjetivo('simplista',-3).
elementoSubjetivo('siniestro',-3).
elementoSubjetivo('sinopsis',-3).
elementoSubjetivo('snob',-3).
elementoSubjetivo('soborno',-3).
elementoSubjetivo('sobrecogido',-3).
elementoSubjetivo('socavar',-3).
elementoSubjetivo('socorro',-3).
elementoSubjetivo('sofocar',-3).
elementoSubjetivo('soga',-3).
elementoSubjetivo('soledad',-3).
elementoSubjetivo('solitario',-3).
elementoSubjetivo('solo',-3).
elementoSubjetivo('solterona',-3).
elementoSubjetivo('sombrÌo',-3).
elementoSubjetivo('someter',-3).
elementoSubjetivo('somnolencia',-3).
elementoSubjetivo('sonajero',-3).
elementoSubjetivo('soportar',-3).
elementoSubjetivo('sordera',-3).
elementoSubjetivo('sordo',-3).
elementoSubjetivo('sore',-3).
elementoSubjetivo('sorna',-3).
elementoSubjetivo('sorpresa',-3).
elementoSubjetivo('soso',-3).
elementoSubjetivo('sospechar',-3).
elementoSubjetivo('sospechoso',-3).
elementoSubjetivo('sostener',-3).
elementoSubjetivo('subir',-3).
elementoSubjetivo('suburbio',-3).
elementoSubjetivo('subversiÛn',-3).
elementoSubjetivo('subvertir',-3).
elementoSubjetivo('subyugaciÛn',-3).
elementoSubjetivo('subyugar',-3).
elementoSubjetivo('suciedad',-3).
elementoSubjetivo('sucio',-3).
elementoSubjetivo('sucumbe',-3).
elementoSubjetivo('suerte',-3).
elementoSubjetivo('sufrimiento',-3).
elementoSubjetivo('sufrir',-3).
elementoSubjetivo('suicidio',-3).
elementoSubjetivo('sujeciÛn',-3).
elementoSubjetivo('sumisiÛn',-3).
elementoSubjetivo('sumiso',-3).
elementoSubjetivo('superaciÛn',-3).
elementoSubjetivo('superficial',-3).
elementoSubjetivo('superficialidad',-3).
elementoSubjetivo('superflua',-3).
elementoSubjetivo('supersticiÛn',-3).
elementoSubjetivo('supersticioso',-3).
elementoSubjetivo('supervisiÛn',-3).
elementoSubjetivo('suplemento',-3).
elementoSubjetivo('suprimir',-3).
elementoSubjetivo('suspender',-3).
elementoSubjetivo('suspensiÛn',-3).
elementoSubjetivo('sustituciÛn',-3).
elementoSubjetivo('tÌmido',-3).
elementoSubjetivo('tÛxico',-3).
elementoSubjetivo('tab˙',-3).
elementoSubjetivo('tabaco',-3).
elementoSubjetivo('tanque',-3).
elementoSubjetivo('tardÌo',-3).
elementoSubjetivo('tarde',-3). %solo si es adverbio
elementoSubjetivo('tarifa',-3).
elementoSubjetivo('tedioso',-3).
elementoSubjetivo('temer',-3).
elementoSubjetivo('temeroso',-3).
elementoSubjetivo('temible',-3).
elementoSubjetivo('temor',-3).
elementoSubjetivo('temporalmente',-3).
elementoSubjetivo('tensar',-3).
elementoSubjetivo('tensiÛn',-3).
elementoSubjetivo('tenso',-3).
elementoSubjetivo('tentaciÛn',-3).
elementoSubjetivo('tergiversar',-3).
elementoSubjetivo('termita',-3).
elementoSubjetivo('terquedad',-3).
elementoSubjetivo('terrible',-3).
elementoSubjetivo('terror',-3).
elementoSubjetivo('terrorismo',-3).
elementoSubjetivo('terrorista',-3).
elementoSubjetivo('testarudo',-3).
elementoSubjetivo('tiburÛn',-3).
elementoSubjetivo('tic',-3).
elementoSubjetivo('tieso',-3).
elementoSubjetivo('timidez',-3).
elementoSubjetivo('tiranÌa',-3).
elementoSubjetivo('tirar',-3).
elementoSubjetivo('tomar',-3).
elementoSubjetivo('tonterÌas',-3).
elementoSubjetivo('tonto',-3).
elementoSubjetivo('toque',-3).
elementoSubjetivo('tormenta',-3).
elementoSubjetivo('tormento',-3).
elementoSubjetivo('tornado',-3).
elementoSubjetivo('torpe',-3).
elementoSubjetivo('torpeza',-3).
elementoSubjetivo('tortura',-3).
elementoSubjetivo('tosquedad',-3).
elementoSubjetivo('tr·gico',-3).
elementoSubjetivo('tragedia',-3).
elementoSubjetivo('traiciÛn',-3).
elementoSubjetivo('traicionar',-3).
elementoSubjetivo('traicionero',-3).
elementoSubjetivo('traidor',-3).
elementoSubjetivo('trampa',-3).
elementoSubjetivo('transgredir',-3).
elementoSubjetivo('traspasar',-3).
elementoSubjetivo('trastorno',-3).
elementoSubjetivo('trato',-3).
elementoSubjetivo('traum·tico',-3).
elementoSubjetivo('trauma',-3).
elementoSubjetivo('traumas',-3).
elementoSubjetivo('travieso',-3).
elementoSubjetivo('triste',-3).
elementoSubjetivo('tristeza',-3).
elementoSubjetivo('trivial',-3).
elementoSubjetivo('tullido',-3).
elementoSubjetivo('tumba',-3).
elementoSubjetivo('tumor',-3).
elementoSubjetivo('turbio',-3).
elementoSubjetivo('turbulencia',-3).
elementoSubjetivo('turbulento',-3).
elementoSubjetivo('ultim·tum',-3).
elementoSubjetivo('usar',-3).
elementoSubjetivo('usurpar',-3).
elementoSubjetivo('v·ndalo',-3).
elementoSubjetivo('vÌctima',-3).
elementoSubjetivo('vÛmito',-3).
elementoSubjetivo('vaciar',-3).
elementoSubjetivo('vacilaciÛn',-3).
elementoSubjetivo('vacilar',-3).
elementoSubjetivo('vagabond',-3).
elementoSubjetivo('vagabundos',-3).
elementoSubjetivo('vago',-3).
elementoSubjetivo('vaguedad',-3).
elementoSubjetivo('vampiro',-3).
elementoSubjetivo('vanidad',-3).
elementoSubjetivo('vanidoso',-3).
elementoSubjetivo('vano',-3).
elementoSubjetivo('vehemente',-3).
elementoSubjetivo('vencido',-3).
elementoSubjetivo('veneno',-3).
elementoSubjetivo('venenoso',-3).
elementoSubjetivo('venenosos',-3).
elementoSubjetivo('vengar',-3).
elementoSubjetivo('venom',-3).
elementoSubjetivo('verg¸enza',-3).
elementoSubjetivo('vergonzoso',-3).
elementoSubjetivo('vertedero',-3).
elementoSubjetivo('vetar',-3).
elementoSubjetivo('vicio',-3).
elementoSubjetivo('vicioso',-3).
elementoSubjetivo('victimismo',-3).
elementoSubjetivo('vigilancia',-3).
elementoSubjetivo('violaciÛn',-3).
elementoSubjetivo('violar',-3).
elementoSubjetivo('violatorio',-3).
elementoSubjetivo('violencia',-3).
elementoSubjetivo('violento',-3).
elementoSubjetivo('viruela',-3).
elementoSubjetivo('vol·tiles',-3).
elementoSubjetivo('volatilidad',-3).
elementoSubjetivo('volc·n',-3).
elementoSubjetivo('volcar',-3).
elementoSubjetivo('voluble',-3).
elementoSubjetivo('vulgar',-3).
elementoSubjetivo('vulnerabilidad',-3).
elementoSubjetivo('vulnerable',-3).
elementoSubjetivo('zanja',-3).
elementoSubjetivo('zopenco',-3).
elementoSubjetivo('zurra',-3).

%%%% positivos (todos tomados de Redondo: 360, falta buscar en el General Inquirer y traducir)

elementoSubjetivo('abrazo',3).
elementoSubjetivo('abundancia',3).
elementoSubjetivo('acogedor',3).
elementoSubjetivo('acuerdo',3).
elementoSubjetivo('acurrucarse',3).
elementoSubjetivo('adinerado',3).
elementoSubjetivo('admirado',3).
elementoSubjetivo('adorable',3).
elementoSubjetivo('afecto',3).
elementoSubjetivo('afortunado',3).
elementoSubjetivo('agilidad',3).
elementoSubjetivo('agradecido',3).
elementoSubjetivo('agua',3).
elementoSubjetivo('ahorrar',3).
elementoSubjetivo('aire',3).
elementoSubjetivo('alba',3).
elementoSubjetivo('alegre',3).
elementoSubjetivo('almohada',3).
elementoSubjetivo('amabilidad',3).
elementoSubjetivo('amable',3).
elementoSubjetivo('amado',3).
elementoSubjetivo('amanecer',3).
elementoSubjetivo('amigable',3).
elementoSubjetivo('amigo',3).
elementoSubjetivo('amor',3).
elementoSubjetivo('·ngel',3).
elementoSubjetivo('·nimo',3).
elementoSubjetivo('aplausos',3).
elementoSubjetivo('aprender',3).
elementoSubjetivo('aprobaciÛn',3).
elementoSubjetivo('·rbol',3).
elementoSubjetivo('arco-iris',3).
elementoSubjetivo('arte',3).
elementoSubjetivo('as',3).
elementoSubjetivo('·tico',3).
elementoSubjetivo('atrevido',3).
elementoSubjetivo('aurora',3).
elementoSubjetivo('aventura',3).
elementoSubjetivo('aviÛn',3).
elementoSubjetivo('az˙car',3).
elementoSubjetivo('azul',3).
elementoSubjetivo('bailarÌn',3).
elementoSubjetivo('baÒera',3).
elementoSubjetivo('baÒo',3).
elementoSubjetivo('bar',3).
elementoSubjetivo('bebÈ',3).
elementoSubjetivo('bebida',3).
elementoSubjetivo('belleza',3).
elementoSubjetivo('beso',3).
elementoSubjetivo('bien',3).
elementoSubjetivo('blanco',3).
elementoSubjetivo('boda',3).
elementoSubjetivo('brillante',3).
elementoSubjetivo('brisa',3).
elementoSubjetivo('bueno',3).
elementoSubjetivo('caballo',3).
elementoSubjetivo('cachorro',3).
elementoSubjetivo('calidad',3).
elementoSubjetivo('calmar',3).
elementoSubjetivo('cama',3).
elementoSubjetivo('campeÛn',3).
elementoSubjetivo('campo',3).
elementoSubjetivo('canciÛn',3).
elementoSubjetivo('capaz',3).
elementoSubjetivo('cara',3).
elementoSubjetivo('caramelo',3).
elementoSubjetivo('caricia',3).
elementoSubjetivo('cariÒoso',3).
elementoSubjetivo('carta',3).
elementoSubjetivo('casa',3).
elementoSubjetivo('cascada',3).
elementoSubjetivo('casita',3).
elementoSubjetivo('cena',3).
elementoSubjetivo('cÈsped',3).
elementoSubjetivo('chico',3).
elementoSubjetivo('chiste',3).
elementoSubjetivo('chocolate',3).
elementoSubjetivo('cielo',3).
elementoSubjetivo('circo',3).
elementoSubjetivo('coche',3).
elementoSubjetivo('coito',3).
elementoSubjetivo('color',3).
elementoSubjetivo('comedia',3).
elementoSubjetivo('comer',3).
elementoSubjetivo('comida',3).
elementoSubjetivo('comprometido',3).
elementoSubjetivo('concentrado',3).
elementoSubjetivo('conejito',3).
elementoSubjetivo('conejo',3).
elementoSubjetivo('confianza',3).
elementoSubjetivo('confort',3).
elementoSubjetivo('conocimiento',3).
elementoSubjetivo('considerado',3).
elementoSubjetivo('convencido',3).
elementoSubjetivo('corazÛn',3).
elementoSubjetivo('correo',3).
elementoSubjetivo('cortesÌa',3).
elementoSubjetivo('costa',3).
elementoSubjetivo('crepe',3).
elementoSubjetivo('crep˙sculo',3).
elementoSubjetivo('cuerpo',3).
elementoSubjetivo('cumpleaÒos',3).
elementoSubjetivo('curar',3).
elementoSubjetivo('decorar',3).
elementoSubjetivo('dedicado',3).
elementoSubjetivo('defendido',3).
elementoSubjetivo('deleite',3).
elementoSubjetivo('deportes',3).
elementoSubjetivo('descanso',3).
elementoSubjetivo('desenfadado',3).
elementoSubjetivo('deseo',3).
elementoSubjetivo('detalle',3).
elementoSubjetivo('diamante',3).
elementoSubjetivo('dicha',3).
elementoSubjetivo('digno',3).
elementoSubjetivo('dinero',3).
elementoSubjetivo('diploma',3).
elementoSubjetivo('diversiÛn',3).
elementoSubjetivo('dormir',3).
elementoSubjetivo('educaciÛn',3).
elementoSubjetivo('efectivo',3).
elementoSubjetivo('elegante',3).
elementoSubjetivo('empleo',3).
elementoSubjetivo('enamorado',3).
elementoSubjetivo('encanto',3).
elementoSubjetivo('enÈrgico',3).
elementoSubjetivo('ensalada',3).
elementoSubjetivo('entusiasmo',3).
elementoSubjetivo('erÛtico',3).
elementoSubjetivo('escritor',3).
elementoSubjetivo('espacio',3).
elementoSubjetivo('esperanza',3).
elementoSubjetivo('esperanzado',3).
elementoSubjetivo('esposo',3).
elementoSubjetivo('espuma',3).
elementoSubjetivo('estrella',3).
elementoSubjetivo('estufa',3).
elementoSubjetivo('eufÛrico',3).
elementoSubjetivo('excelencia',3).
elementoSubjetivo('excitado',3).
elementoSubjetivo('Èxito',3).
elementoSubjetivo('exquisito',3).
elementoSubjetivo('exterior',3).
elementoSubjetivo('extraordinario',3).
elementoSubjetivo('f·cil',3).
elementoSubjetivo('familia',3).
elementoSubjetivo('fantasÌa',3).
elementoSubjetivo('fascinar',3).
elementoSubjetivo('favor',3).
elementoSubjetivo('feliz',3).
elementoSubjetivo('festivo',3).
elementoSubjetivo('fiesta',3).
elementoSubjetivo('firmamento',3).
elementoSubjetivo('flor',3).
elementoSubjetivo('florecer',3).
elementoSubjetivo('fragancia',3).
elementoSubjetivo('fuerte',3).
elementoSubjetivo('ganancias',3).
elementoSubjetivo('ganar',3).
elementoSubjetivo('gatito',3).
elementoSubjetivo('gato',3).
elementoSubjetivo('generoso',3).
elementoSubjetivo('genial',3).
elementoSubjetivo('gente',3).
elementoSubjetivo('gloria',3).
elementoSubjetivo('goce',3).
elementoSubjetivo('graduado',3).
elementoSubjetivo('guapa',3).
elementoSubjetivo('guapo',3).
elementoSubjetivo('guarderÌa',3).
elementoSubjetivo('guiÒo',3).
elementoSubjetivo('hermano',3).
elementoSubjetivo('hermoso',3).
elementoSubjetivo('hogar',3).
elementoSubjetivo('hombre',3).
elementoSubjetivo('honesto',3).
elementoSubjetivo('honor',3).
elementoSubjetivo('hotel',3).
elementoSubjetivo('humano',3).
elementoSubjetivo('humilde',3).
elementoSubjetivo('humor',3).
elementoSubjetivo('idea',3).
elementoSubjetivo('identidad',3).
elementoSubjetivo('Ìdolo',3).
elementoSubjetivo('imaginar',3).
elementoSubjetivo('importante',3).
elementoSubjetivo('impresionado',3).
elementoSubjetivo('incentivo',3).
elementoSubjetivo('ingenio',3).
elementoSubjetivo('inocente',3).
elementoSubjetivo('inspirado',3).
elementoSubjetivo('inspirar',3).
elementoSubjetivo('intelecto',3).
elementoSubjetivo('interÈs',3).
elementoSubjetivo('Ìntimo',3).
elementoSubjetivo('invitaciÛn',3).
elementoSubjetivo('jardÌn',3).
elementoSubjetivo('joven',3).
elementoSubjetivo('jovial',3).
elementoSubjetivo('joya',3).
elementoSubjetivo('j˙bilo',3).
elementoSubjetivo('jubiloso',3).
elementoSubjetivo('juego',3).
elementoSubjetivo('juguete',3).
elementoSubjetivo('justicia',3).
elementoSubjetivo('juventud',3).
elementoSubjetivo('lago',3).
elementoSubjetivo('leal',3).
elementoSubjetivo('leyenda',3).
elementoSubjetivo('liberaciÛn',3).
elementoSubjetivo('libertad',3).
elementoSubjetivo('libre',3).
elementoSubjetivo('libro',3).
elementoSubjetivo('licenciado',3).
elementoSubjetivo('logro',3).
elementoSubjetivo('loterÌa',3).
elementoSubjetivo('lujo',3).
elementoSubjetivo('madre',3).
elementoSubjetivo('magdalena',3).
elementoSubjetivo('m·gico',3).
elementoSubjetivo('magistral',3).
elementoSubjetivo('mano',3).
elementoSubjetivo('maravilla',3).
elementoSubjetivo('mariposa',3).
elementoSubjetivo('mascota',3).
elementoSubjetivo('mejorar',3).
elementoSubjetivo('melodÌa',3).
elementoSubjetivo('memoria',3).
elementoSubjetivo('mente',3).
elementoSubjetivo('milagro',3).
elementoSubjetivo('millonario',3).
elementoSubjetivo('modesto',3).
elementoSubjetivo('moneda',3).
elementoSubjetivo('montaÒa',3).
elementoSubjetivo('moral',3).
elementoSubjetivo('movilidad',3).
elementoSubjetivo('mujer',3).
elementoSubjetivo('mundo',3).
elementoSubjetivo('muÒeca',3).
elementoSubjetivo('museo',3).
elementoSubjetivo('m˙sica',3).
elementoSubjetivo('natural',3).
elementoSubjetivo('naturaleza',3).
elementoSubjetivo('navidad',3).
elementoSubjetivo('nÈctar',3).
elementoSubjetivo('nene',3).
elementoSubjetivo('nieve',3).
elementoSubjetivo('niÒo',3).
elementoSubjetivo('novia',3).
elementoSubjetivo('novio',3).
elementoSubjetivo('nubes',3).
elementoSubjetivo('nutrir',3).
elementoSubjetivo('obsequio',3).
elementoSubjetivo('ocaso',3).
elementoSubjetivo('ocÈano',3).
elementoSubjetivo('opciÛn',3).
elementoSubjetivo('opiniÛn',3).
elementoSubjetivo('oportunidad',3).
elementoSubjetivo('optimismo',3).
elementoSubjetivo('ordenado',3).
elementoSubjetivo('orgasmo',3).
elementoSubjetivo('oro',3).
elementoSubjetivo('orquesta',3).
elementoSubjetivo('padre',3).
elementoSubjetivo('p·jaro',3).
elementoSubjetivo('palacio',3).
elementoSubjetivo('paloma',3).
elementoSubjetivo('paraÌso',3).
elementoSubjetivo('pareja',3).
elementoSubjetivo('pasiÛn',3).
elementoSubjetivo('pasta',3).
elementoSubjetivo('pastel',3).
elementoSubjetivo('paz',3).
elementoSubjetivo('pelÌcula',3).
elementoSubjetivo('perfecciÛn',3).
elementoSubjetivo('perfume',3).
elementoSubjetivo('perro',3).
elementoSubjetivo('persona',3).
elementoSubjetivo('pezÛn',3).
elementoSubjetivo('piel',3).
elementoSubjetivo('pintura',3).
elementoSubjetivo('pizza',3).
elementoSubjetivo('placer',3).
elementoSubjetivo('planta',3).
elementoSubjetivo('playa',3).
elementoSubjetivo('poesÌa',3).
elementoSubjetivo('pradera',3).
elementoSubjetivo('prestigio',3).
elementoSubjetivo('primavera',3).
elementoSubjetivo('privacidad',3).
elementoSubjetivo('progreso',3).
elementoSubjetivo('protegido',3).
elementoSubjetivo('pueblo',3).
elementoSubjetivo('radiante',3).
elementoSubjetivo('radio',3).
elementoSubjetivo('ramo',3).
elementoSubjetivo('recompensa',3).
elementoSubjetivo('reconocido',3).
elementoSubjetivo('recuerdos',3).
elementoSubjetivo('regalo',3).
elementoSubjetivo('relajado',3).
elementoSubjetivo('rescate',3).
elementoSubjetivo('respeto',3).
elementoSubjetivo('respetuoso',3).
elementoSubjetivo('restaurante',3).
elementoSubjetivo('rÌo',3).
elementoSubjetivo('riqueza',3).
elementoSubjetivo('risa',3).
elementoSubjetivo('rom·ntico',3).
elementoSubjetivo('ropa',3).
elementoSubjetivo('sabio',3).
elementoSubjetivo('sabor',3).
elementoSubjetivo('salud  ',3).
elementoSubjetivo('saludar',3).
elementoSubjetivo('saludo',3).
elementoSubjetivo('salvador',3).
elementoSubjetivo('satisfecho',3).
elementoSubjetivo('satisfacciÛn',3).
elementoSubjetivo('seda',3).
elementoSubjetivo('seguro',3).
elementoSubjetivo('sentimiento',3).
elementoSubjetivo('sexo',3).
elementoSubjetivo('sexy',3).
elementoSubjetivo('simp·tico',3).
elementoSubjetivo('sociable',3).
elementoSubjetivo('sol',3).
elementoSubjetivo('soleado',3).
elementoSubjetivo('sonajero',3).
elementoSubjetivo('sorprendido',3).
elementoSubjetivo('suave',3).
elementoSubjetivo('sueÒo',3).
elementoSubjetivo('talento',3).
elementoSubjetivo('tarta',3).
elementoSubjetivo('tesoro',3).
elementoSubjetivo('tierno',3).
elementoSubjetivo('tobog·n',3).
elementoSubjetivo('tolerante',3).
elementoSubjetivo('tranquilo',3).
elementoSubjetivo('travesura',3).
elementoSubjetivo('triunfante',3).
elementoSubjetivo('triunfo',3).
elementoSubjetivo('trofeo',3).
elementoSubjetivo('˙til',3).
elementoSubjetivo('vacaciÛn',3).
elementoSubjetivo('valiente',3).
elementoSubjetivo('vehÌculo',3).
elementoSubjetivo('velero',3).
elementoSubjetivo('vencedor',3).
elementoSubjetivo('ventaja',3).
elementoSubjetivo('verdad',3).
elementoSubjetivo('verde',3).
elementoSubjetivo('vestido',3).
elementoSubjetivo('viajes',3).
elementoSubjetivo('victoria',3).
elementoSubjetivo('vida',3).
elementoSubjetivo('violÌn',3).
elementoSubjetivo('virtud',3).
elementoSubjetivo('visiÛn',3).
elementoSubjetivo('vivo',3).
elementoSubjetivo('yate',3).
elementoSubjetivo('zafiro',3).